### ISSUE TITLE
Unity freeze under Linux

### ISSUE THREAD

**Issue by PonemanTL** [naelstrof/KoboldKare#179]
Running Unity 2021.3.6f1 (or now 2021.3.19f1 with current master) the KK project causes Unity's main window to freeze, once it finishes opening. CPU use is pegged at 100% on one core, the window doesn't respond, and closing the process with a polite signal 15 (sigterm) does nothing, I have to forcibly unload it with a kill -9 (sigkill).
 Bisecting shows the problem began with commit b9c5dc64e193 on February 4th. Before that it opens just fine. It's a big commit, so I'm not sure what change is causing the issue.

**Comment by naelstrof** [comment]
Oh thank you for using bisect to figure out when the issue started I know exactly what's going on. I actually get the freeze specifically when TextMeshPro's or Photon's required asset isn't findable within the Addressables.

For whatever reason, restarting the editor fixed it for me and I haven't struggled with it since.
It has to do with the fact that I had to completely remove Resources use in order for text assets to work properly in the new addressables system.

Both TextMeshPro, and Photon uses Resources to load their settings and some default assets.

Here's one example:

https://github.com/naelstrof/KoboldKare/blob/13c12f7622f5c93928bc67e745362e3285771356/Packages/com.unity.textmeshpro/Scripts/Runtime/TMP_ResourcesManager.cs#L32

You can search for all instances of "WaitForCompletion" in the project and you'll find all the edits I've made.

The `WaitForCompletion()` blocks until the asset is loaded (or if it fails to load). There's an Addressables bug that makes this event never fire so it ends up hanging forever. This only happened a few times for me, it's possible that depending on your Addressables simulation setting that it might break forever. I work on KoboldKare with Addressables set to "[Use Asset Database (fast)](https://docs.unity3d.com/Packages/com.unity.addressables@1.3/manual/AddressableAssetsDevelopmentCycle.html)", any other setting might proc this issue.

A proper fix would be to make both Photon and TextMeshPro more asynchronous, or to retrofit them better. I definitely want to fix this properly, I'm still in the middle of prototyping some moddable addressables.

**Comment by PonemanTL** [comment]
Hmm, nope, "use database asset (fast) is already in there, it's part of the default settings in the project's git repo which are presumably copied from yours. it doesn't seem to help, it still freezes hard.

**Comment by naelstrof** [comment]
Gotcha, thanks for double checking. I'll refactor how photon and text mesh pro loads to hopefully be more bug-free. Addressables probably isn't expecting code to try to load assets during domain switches.

**Comment by naelstrof** [comment]
Found patch notes for Addressables 1.20.3:
> Fixed bug where WaitForCompletion could hang indefinitely under certain race conditions (primarily on Android)
> Fixed a bug where calling WaitForCompletion on a LoadAssetAsync call that was loading from Resources would freeze the editor.

Sounds like it describes this exact issue (trying to load resources via addressables with WaitForCompletion). 

Could you check if the bug is still happening?

**Comment by PonemanTL** [comment]
Looks like 29faa37 did the trick! Loads up fine now.

**Comment by naelstrof** [comment]
Awesome, thank you. Without your bisect I'm not sure I would've found such a clean solution.

**Comment by PonemanTL** [comment]
No problem. I may not know much about Unity, but I know git inside and out.
