### ISSUE TITLE
Scanner gets stuck

### ISSUE THREAD

**Issue by Godeken** [naelstrof/KoboldKare#190]
When using the scanner inside one of the barns, if you happen to bump it upside down, it gets stuck in the flooring
![image](https://user-images.githubusercontent.com/121225143/222895603-dd7f37f3-5a10-43da-8fcf-5b152edc5d40.png)

**Comment by TheKnightofAura** [comment]
Can confirm: I've lost so many scanners inside the kitchen barn....

**Comment by naelstrof** [comment]
This was due to the two-sided planks causing the physics engine to not be sure which way to depenetrate objects.

I just did a proper fix by roughing out a sealed manifold collider like so:
![image](https://user-images.githubusercontent.com/1131571/222939679-fcc17274-33d6-4171-b892-3b827e53a8b4.png)

It's not as accurate, but stuff doesn't get stuck randomly in it anymore.
