### ISSUE TITLE
Expired Milk

### ISSUE THREAD

**Issue by OfficialMonsterCrush** [naelstrof/KoboldKare#198]
Once getting a Kobold pregnant no matter the sex or how far into the egg stage they are, if the individual drinks milk it completely takes over hard cancelling the pregnancy's progress replacing it with a indicator that's similar to yogurt or melon juice

**Comment by Godeken** [comment]
The stomach is like a container... if you mix cum and milk, you get yogurt (turns purple)... if the cum has gestated, it wont turn into yogurt because the cum turns into an egg... 

However... if your full, and you add water as an example, you overwrite some of the other items in the stomach to make space for the water... not sure the logic behind other liquids squash others but it works well... just dont go near milk until everything in the stomach has become egg
