### ISSUE TITLE
Equipment disappears during save and load

### ISSUE THREAD

**Issue by Godeken** [naelstrof/KoboldKare#207]
Saved game with Equipment on: (playing through Unity) 
[NSFWimage](https://user-images.githubusercontent.com/121225143/225147984-87b0df75-b565-4597-b746-1cbac8aee230.png)

Closed game and reloaded:
[NSFWimage](https://user-images.githubusercontent.com/121225143/225148135-9d9306c7-3b11-4bdc-ab98-50462ee5fcb7.png)

Hat is showing, but it doesnt actually exist on the character... (not in inventory and cant unequip)

**Comment by OfficialMonsterCrush** [comment]
yeah this has been happening to me as well, still been trying to find out why it does it

**Comment by naelstrof** [comment]
Figured it out, it's because I accidentally added two sets of KoboldInventory. It would randomly order the serialization which would randomly remove items.

Using the `/equip` command rather than picking items up off the floor was the key, as it proc'd an error pointing out the duplicated behaviors.
