### ISSUE TITLE
Nipple pump not working + vague/misleading quest text

### ISSUE THREAD

**Issue by cooperdk** [naelstrof/KoboldKare#210]
Now, I spawned it using the console, but I imagine it should work since it's available.

But there's absolutely no description as to how to use it.

Also, the quests are INCREDIBLY vague and sometimes even misleading.

**Comment by naelstrof** [comment]
Yeah there should be no way to get nipple pumps without hacks. The shop items right now are all shuffled due to the recent modding improvements-- so they might show up inappropriately right now. I'll delete them proper and close this issue when I do.

I have no plans to improve the game's onboarding at the moment.

**Comment by Godeken** [comment]
Quests misleading? Which ones? I got to max star last night... so i dont understand... they are 100% english 🤣
